export const SET_PAGINATION = 'SET_PAGINATION';
export const SET_QUERY = 'SET_QUERY';

export const FIND_DATA = 'FIND_DATA';
export const FIND_DATA_SUCCESS = 'FIND_DATA_SUCCESS';

export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

export const UPDATE_ITEM = 'UPDATE_ITEM';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';

export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';

export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';

export const SET_NEW = 'SET_NEW';
export const SET_LOCK = 'SET_LOCK';
export const EDITOR_CHANGED = 'EDITOR_CHANGED';
